version: "{build}"

clone_folder: c:\gopath\src\github.com\choria-io\go-choria

environment:
  GOPATH: c:\gopath
  GOVERSION: "1.15"
  MCOLLECTIVE_CERTNAME: rip.mcollective
  RUBY_VERSION: 24
  CGO_ENABLED: 0

init:
  - git config --global core.autocrlf input

before_test:
  - ruby -v

install:
  # Install the specific Go version.
  - rmdir c:\go /s /q
  - appveyor DownloadFile https://storage.googleapis.com/golang/go%GOVERSION%.windows-amd64.msi
  - msiexec /i go%GOVERSION%.windows-amd64.msi /q
  - set Path=C:\Ruby%RUBY_VERSION%\bin;c:\go\bin;c:\gopath\bin;%Path%
  # Install vendor dependencies
  - go get github.com/onsi/ginkgo/ginkgo

build: false
deploy: false

test_script:
  # TODO: support windows pkcs11sec
  - ginkgo -r -keepGoing -skipMeasurements -skipPackage pkcs11sec
