required_properties:
  - name
  - bindir
  - etcdir
  - manage_conf
  - contact
  - dist
  - target_arch
  - rpm_group
  - server_start_level

artifacts:
 - /usr/src/redhat/**/*.rpm
 - /root/rpmbuild/**/*.rpm
